name: Run Node.js script on a dispatch

on:
  push:
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install
      - name: Run script
        run: npm start
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CONFIG: ${{ secrets.CONFIG }}
          FETCH_CHANNELS_COUNT: ${{ secrets.FETCH_CHANNELS_COUNT }}
